# Bar Graph
# Automatically generated by Colaboratory.

"""Distribution of Free and Paid Apps on Google Play Store"""


import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv("/content/googleplaystoreapps.csv")
type_counts = df['Type'].value_counts()

plt.figure(figsize=(8, 6))
colors = ['skyblue', 'lightcoral']
plt.bar(type_counts.index, type_counts, color=colors)
plt.xlabel('Type')
plt.ylabel('Number of Apps')
plt.title('Distribution of Free and Paid Apps on Google Play Store')
plt.show()

"""Worst 5 Paid Apps on Google Play Store based on Rating"""


df = pd.read_csv("/content/googleplaystoreapps.csv")
paid = df[df['Price'] != '0']
worst = paid.sort_values(by='Rating', ascending=True).head(5)

plt.figure(figsize=(10, 6))
plt.barh(worst['App'], worst['Rating'], color='red')
plt.xlabel('Rating')
plt.ylabel("App")
plt.title('Worst 5 Paid Apps on Google Play Store based on Rating')
plt.xlim(0, 5)
plt.show()

"""Top 7 Apps in Finance Category with Ratings 1 to 2"""


df = pd.read_csv("/content/googleplaystoreapps.csv")
finance = df[df['Category'] == 'FINANCE'].copy()
finance['Rating'] = pd.to_numeric(finance['Rating'], errors='coerce')
filtered = finance[(finance['Rating'] >= 1) & (finance['Rating'] <= 2)].copy()
top_apps = filtered.sort_values(by='Installs', ascending=False).head(7)

plt.figure(figsize=(12, 8))
plt.bar(top_apps['App'], top_apps['Installs'], color='y')
plt.xlabel('App')
plt.ylabel('Number of Installs')
plt.title('Top 7 Apps in Finance Category with Ratings 1 to 2')
plt.xticks(rotation=45, ha='right')
plt.show()

"""Top 10 Categories with the Highest Number of Apps on Google Play Store"""


df = pd.read_csv("/content/googleplaystoreapps.csv")
category = df['Category'].value_counts()
topcategories = category.head(10)

plt.figure(figsize=(12, 8))
topcategories.plot(kind='bar', color='purple')
plt.xlabel('Category')
plt.ylabel('Number of Apps')
plt.title('Top 10 Categories with the Highest Number of Apps on Google Play Store')
plt.xticks(rotation=45, ha='right')
plt.show()

"""Number of Apps with Content Rating "Everyone" in Each Category"""


df = pd.read_csv("/content/googleplaystoreapps.csv")
everyone = df[df['Content Rating'] == 'Everyone']
category = everyone['Category'].value_counts()
categories = category.index
counts = category.values

plt.figure(figsize=(12, 8))
plt.bar(categories, counts, color='green')
plt.xlabel('Category')
plt.ylabel('Number of Apps')
plt.title('Number of Apps with Content Rating "Everyone" in Each Category')
plt.xticks(rotation=45, ha='right')
plt.show()
