# Histogram Plot
# Automatically generated by Colaboratory.

"""Distribution of Apps Across Different Content Ratings"""


import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv("/content/googleplaystoreapps.csv")

plt.figure(figsize=(12, 8))
plt.hist(df['Content Rating'], bins=df['Content Rating'].nunique(),
         color='purple', edgecolor='black', align='mid')
plt.xlabel('Content Rating')
plt.ylabel('Number of Apps')
plt.title('Distribution of Apps Across Different Content Ratings')
plt.xticks(rotation=45, ha='right')
plt.show()

"""Distribution of App Ratings on Google Play Store"""


df = pd.read_csv("/content/googleplaystoreapps.csv")
df['Rating'] = pd.to_numeric(df['Rating'], errors='coerce')

ratings = df['Rating'].dropna()
plt.figure(figsize=(10, 6))
plt.hist(ratings, bins=30, color='skyblue', edgecolor='black')
plt.xlabel('Rating')
plt.ylabel('Frequency')
plt.title('Distribution of App Ratings on Google Play Store')
plt.show()

"""Distribution of App Sizes Between 50 and 100 MB on Google Play Store"""


df = pd.read_csv("/content/googleplaystoreapps.csv")
df['Size'] = df['Size'].replace('Varies with device', pd.NA)
df['Size'] = pd.to_numeric(df['Size'].str.replace(
    '[\sMk,]', '', regex=True), errors='coerce')
filtered = df[(df['Size'] >= 50) & (df['Size'] <= 100)]

plt.figure(figsize=(12, 8))
plt.hist(filtered['Size'].dropna(), bins=20, color='coral', edgecolor='black')
plt.xlabel('Size (in MB)')
plt.ylabel('Number of Apps')
plt.title('Distribution of App Sizes Between 50 and 100 MB on Google Play Store')
plt.show()

"""Distribution of App Counts Across Categories on Google Play Store"""


df = pd.read_csv("/content/googleplaystoreapps.csv")
category = df['Category'].value_counts()

plt.figure(figsize=(12, 8))
plt.hist(df['Category'], bins=len(category), color='green', edgecolor='black')
plt.xlabel('Category')
plt.ylabel('Number of Apps')
plt.title('Distribution of App Counts Across Categories on Google Play Store')
plt.xticks(rotation=45, ha='right')
plt.show()

"""Distribution of Last Update Years as a Proportion of Total Apps"""


df = pd.read_csv("/content/googleplaystoreapps.csv")
df['Last Updated'] = pd.to_datetime(df['Last Updated'], errors='coerce')
df = df.dropna(subset=['Last Updated'])
df['Years Since Last Update'] = (pd.to_datetime(
    'today') - df['Last Updated']).dt.days // 365

plt.figure(figsize=(12, 8))
plt.hist(df['Years Since Last Update'],
         bins=df['Years Since Last Update'].nunique(), color='y', edgecolor='black')
plt.xlabel('Years Since Last Update')
plt.ylabel('Number of Apps')
plt.title('Distribution of Last Update Years as a Proportion of Total Apps')
plt.show()
