# Linear Plotting
# Automatically generated by Colaboratory.

"""Trend of Average App Sizes Over Time"""


import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv("/content/googleplaystoreapps.csv")
df['Size'] = df['Size'].replace('Varies with device', pd.NA)
df['Size'] = pd.to_numeric(df['Size'].str.replace(
    '[\sMk,]', '', regex=True), errors='coerce')
df['Last Updated'] = pd.to_datetime(df['Last Updated'], errors='coerce')
df['Year'] = df['Last Updated'].dt.year
average_sizes = df.groupby('Year')['Size'].mean()

plt.figure(figsize=(12, 8))
plt.plot(average_sizes.index, average_sizes, marker='X', linestyle='dashed', color='red',
         linewidth=2, markerfacecolor='blue', markersize=8)
plt.xlabel('Year')
plt.ylabel('Average App Size (in MB)')
plt.title('Trend of Average App Sizes Over Time')
plt.xticks(rotation=45, ha='right')
plt.show()

"""Number of Apps with Increasing Ratings (1-5)"""


df = pd.read_csv("/content/googleplaystoreapps.csv")
df['Rating'] = pd.to_numeric(df['Rating'], errors='coerce')
filtered = df[(df['Rating'] >= 1) & (df['Rating'] <= 5)].copy()
app = filtered.groupby('Rating')['App'].count()

plt.figure(figsize=(10, 6))
plt.plot(app.index, app, marker='X', linestyle='dashed', color='green',
         linewidth=2, markerfacecolor='blue', markersize=8)
plt.xlabel('Rating')
plt.ylabel('Number of Apps')
plt.title('Number of Apps with Increasing Ratings (1-5)')
plt.xticks(rotation=45, ha='right')
plt.show()

"""Mean Last Updated Date Across Different Categories on Google Play Store"""


df = pd.read_csv("/content/googleplaystoreapps.csv")
df['Last Updated'] = pd.to_datetime(df['Last Updated'])
category = df.groupby('Category')['Last Updated'].mean()

plt.figure(figsize=(12, 8))
plt.plot(category.index, category, marker='o',
         color='red', label='Mean Last Updated')
plt.xlabel('Category')
plt.ylabel('Mean Last Updated')
plt.title('Mean Last Updated Date Across Different Categories on Google Play Store')
plt.xticks(rotation=45, ha='right')
plt.legend()
plt.show()
