# Pie Chart
# Automatically generated by Colaboratory.

"""Distribution of App Ratings on Google Play Store"""


import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv("/content/googleplaystoreapps.csv")
df['Rating'] = pd.to_numeric(df['Rating'], errors='coerce')
df['Rating'] = df['Rating'].fillna(0)
df['Rounded_Rating'] = df['Rating'].round().astype(int)

rating = df['Rounded_Rating'].value_counts()
rating = rating.sort_index()
plt.figure(figsize=(8, 8))
plt.pie(rating, labels=rating.index, startangle=45,
        colors=plt.cm.Paired.colors, wedgeprops=dict(edgecolor='black'))
plt.title('Distribution of App Ratings on Google Play Store')
plt.show()

"""Distribution of Apps with Rating and No Rating"""


df = pd.read_csv("/content/googleplaystoreapps.csv")
df['Rating'] = pd.to_numeric(df['Rating'], errors='coerce')

noratings = df[df['Rating'].isna()]
otherratings = df[df['Rating'].notna() & (df['Rating'] >= 1)
                  & (df['Rating'] <= 5)]
nocount = len(noratings)
othercount = len(otherratings)
labels = ['No Rating', 'Rated Between 1-5']
sizes = [nocount, othercount]
colors = ['red', 'blue']
explode = (0.05, 0)

plt.figure(figsize=(8, 8))
plt.pie(sizes, explode=explode, labels=labels,
        colors=colors, autopct='%1.1f%%', startangle=150,)
plt.title('Distribution of Apps with Rating and No Rating')
plt.show()

"""Distribution of Free and Paid Apps in the "Family" Category"""


df = pd.read_csv("/content/googleplaystoreapps.csv")
family_apps = df[df['Category'] == 'FAMILY']
type_counts = family_apps['Type'].value_counts()

plt.figure(figsize=(8, 8))
plt.pie(type_counts, labels=type_counts.index, autopct='%1.1f%%', startangle=90, colors=['green', 'orange'],
        wedgeprops=dict(edgecolor='black'))
plt.title('Distribution of Free and Paid Apps in the "Family" Category')
plt.show()

"""Average Ratings of Apps Based on Content Ratings"""


df = pd.read_csv("/content/googleplaystoreapps.csv")
df['Rating'] = pd.to_numeric(df['Rating'], errors='coerce')
df = df.dropna(subset=['Rating'])

average = df.groupby('Content Rating')['Rating'].mean()
explode = (0.02, 0.02, 0.02, 0.02, 0.02)
plt.figure(figsize=(10, 10))
plt.pie(average, labels=average.index, autopct='%1.1f%%',
        startangle=90, explode=explode)
plt.title('Average Ratings of Apps Based on Content Ratings')
plt.show()

"""Distribution of App Sizes Across Categories"""


df = pd.read_csv("/content/googleplaystoreapps.csv")
df['Size'] = df['Size'].replace('Varies with device', pd.NA)
df['Size'] = pd.to_numeric(df['Size'].str.replace(
    '[\sMk,]', '', regex=True), errors='coerce')
df = df.dropna(subset=['Size'])

plt.figure(figsize=(12, 12))
plt.pie(df.groupby('Category')['Size'].mean(), labels=df['Category'].unique(), autopct='%1.1f%%', startangle=90,
        wedgeprops=dict(edgecolor='black'))
plt.title('Distribution of App Sizes Across Categories')
plt.show()
