# Scatter Plot
# Automatically generated by Colaboratory.

"""Correlation Between Number of Reviews and App Ratings"""


import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv("/content/googleplaystoreapps.csv")
df['Reviews'] = pd.to_numeric(df['Reviews'], errors='coerce')
df = df.dropna(subset=['Reviews', 'Rating'])

plt.figure(figsize=(12, 8))
plt.scatter(x='Reviews', y='Rating', data=df,
            color='skyblue', edgecolor='black', alpha=0.7)
plt.xlabel('Number of Reviews')
plt.ylabel('App Rating')
plt.title('Correlation Between Number of Reviews and App Ratings')
plt.show()

"""Distribution of App Prices Within Each Category"""


df = pd.read_csv("/content/googleplaystoreapps.csv")
df['Price'] = df['Price'].replace('[\$,]', '', regex=True).astype(float)
priced_apps = df[df['Price'] > 0]

plt.figure(figsize=(12, 8))
for category in priced_apps['Category'].unique():
    category_data = priced_apps[priced_apps['Category'] == category]
    plt.scatter(category_data['Category'], category_data['Price'],
                s=category_data['Price']*10, alpha=0.7, label=category)
plt.xlabel('Category')
plt.ylabel('Price')
plt.title('Distribution of App Prices Within Each Category')
plt.xticks(rotation=45, ha='right')
plt.show()
